### ISSUE TITLE
Error: Page not found — Links to Jamf Pro reference MunkiReport FQDN instead of "JAMF_SERVER" FQDN

### ISSUE THREAD

**Issue by dan-snelson** [tuxudo/jamf#4]
First, thank you John for your excellent module; first-class.

Links to Jamf Pro reference the MunkiReport FQDN instead of "JAMF_SERVER" FQDN as specified in .env, resulting in:
Error: Page not found 

Steps to reproduce:
1. Login to MunkiReport
2. Navigate to Listings > Jamf
3. Click any displayed record
4. Click the "View in Jamf" button
5. "Error: Page not found" is displayed
6. Observe the URL is: MunkiReportFQDN/computers.html?id=1&o=r&v=inventory

**Comment by tuxudo** [comment]
Fixed broken view in Jamf bug with version v1.5 of the module

**Comment by dan-snelson** [comment]
Confirmed working.

Thanks, Obi-Tuxudo!
