### ISSUE TITLE
Classic API JSON Bug

### ISSUE THREAD

**Issue by Rukongai** [tuxudo/jamf#5]
Patch related endpoints have broken JSON. Something to do with how XML is turned into JSON on the server. Instead of an array it becomes a hash/dict with one key holding the last value only, all others are missing.

XML response is complete. Is there a way to capture at the very least the patch endpoints as XML and convert them to JSON instead of letting the Classic API do it?

Credit to glenfarclas17 https://macadmins.slack.com/archives/C0EP2SNJX/p1553188123075100?thread_ts=1553175359.046300&cid=C0EP2SNJX

**Comment by Rukongai** [comment]
I don't know if this is clean or not because i'm not a coder to save my life

But I got it all working by using the device storage/partitions code you had above in jamf_helper and adapting it to patches

`          // Process patches section separately as XML because of limitations (bug?) with JSON format
          // Get computer data from Jamf
          $url = "{$jamf_server}/JSSResource/computermanagement/serialnumber/{$Jamf_model->serial_number}";
          $jamf_patching_xml_result = $this->get_jamf_url_xml($url);

          $xml = simplexml_load_string($jamf_patching_xml_result);
          $patch_title_array = []; // Create patch reporting array
          foreach ($xml->patch_reporting->patch_reporting_software_titles->title as $patches) {
              $software_titles = []; // Create software titles array

              // Fill in patch details
              $software_titles["name"] = "$patches->name";
              $software_titles['latest_version'] = "$patches->latest_version";
              $software_titles['installed_version'] = "$patches->installed_version";
              // Add patch to software titles array
              $patch_title_array[] = $software_titles;
          }
        $Jamf_model->patch_reporting_software_titles_management = json_encode($patch_title_array); // Encode the patch title array for processing by the client tab


        // Process patches section separately as XML because of limitations (bug?) with JSON format
        // Get computer data from Jamf
        $url = "{$jamf_server}/JSSResource/computermanagement/serialnumber/{$Jamf_model->serial_number}";
        $jamf_patch_policy_xml_result = $this->get_jamf_url_xml($url);

        $xml = simplexml_load_string($jamf_patch_policy_xml_result);
        $patch_policy_array = []; // Create patch policy array
        foreach ($xml->patch_reporting->patch_policies->patch_policy as $patch_policies) {
            $patch_policy = []; // Create patch titles array

            // Fill in patch details
            $patch_policy['id'] = "$patch_policies->id";
            $patch_policy["name"] = "$patch_policies->name";
            // Add policy to policy array
            $patch_policy_array[] = $patch_policy;
        }
      $Jamf_model->patch_policies_management = json_encode($patch_policy_array); // Encode the patch title array for processing by the client tab`

**Comment by tuxudo** [comment]
That looks pretty good! Make a pull request for it and I'll review/merge it in. You went about fixing it in a similar way that I would have :)

**Comment by Rukongai** [comment]
Sorry for the delay. I've never actually used git except for to profit from other people's work.

Let me know if I bungled anything!

I also tried to implement the logic to set the array to empty if nothing returns
It seems to still be working on my setup.

**Comment by tuxudo** [comment]
PR merged
