### ISSUE TITLE
Search Logic Update

### ISSUE THREAD

**Issue by dan-snelson** [tuxudo/jamf#7]
@tuxudo Per Slack conversation, please update the listing's search logic.

---

I successfully upgraded to MunkiReport Version 5.6.4.4224 some time ago and I’m just now looking at https://FQDN/show/report/jamf/jamf

Drilling down on some of the widgets works as expected …
- Last Check-in: https://FQDN/show/listing/jamf/jamf
- XProtect Definitions Version: https://FQDN/show/listing/jamf/jamf/#2135

… while others result in “Page not found” errors:
- Automatic Login Disabled: https://FQDN/show/listing/jamf/jamfdisable_automatic_login%20=%201
- Purchased or Leased: https://FQDN/show/listing/jamf/jamfpurchased%20=%201
- User Approved Enrollment: https://FQDN/show/listing/jamf/jamfuser_approved_enrollment%20=%200

**Comment by tuxudo** [comment]
Resolved with PR #8
